apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: orderservice
  namespace: monitoring
  labels:
    app: orderservice
spec:
  namespaceSelector:
    matchNames:
      - orderservice
  selector:
    matchLabels:
      app: orderservice
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 15s
